apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: todo-ns
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: todo
        image: charanraj1/mybuild-images:todoapp-v14
        ports:
        - containerPort: 8000
